---
services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    labels:
      traefik.http.services.mailpit.loadbalancer.server.port: 8025
      traefik.http.routers.mailpit.rule: "Host(`mailpit.${FLIGHT_DOMAIN?:}`)"
